### ISSUE TITLE
Webhook support

### ISSUE THREAD

**Issue by abulte** [opendatateam/croquemort#24]
We want `croquemort` to be able to send the results of a check to a registered HTTP endpoint, i.e. a webhook.

**Comment by abulte** [comment]
http://phalt.co/webhooks-in-apis/

**Comment by abulte** [comment]
I was thinking of declaring the callback URL of the webhook (webhook subscription) directly in the check request to croquemort, e.g.:

`http :8000/check/one url="https://www.data.gouv.fr/fr/" callback_url="https://mysite.com/croquemort"`

Webhooks are usually subscribed to via a dedicated endpoint / interface. But this means having a user account system on croquemort - or use the referer as a loose authentication token, but it's probably a bad idea.

@vinyll @davidbgk @noirbizarre @oncletom thoughts?

**Comment by oncletom** [comment]
It's simple and it can work well… until there is a problem, which generates problems on its own.

I implemented webhooks based systems in the past, it's nice, but when there the remote service is down/SSL certificate has issues/a deploy adds a regression/DDoSed by the amount of requests, the backpressure becomes a painpoint, likewise to resume operations and coping with the buffer of unprocessed webhook requests. It's the problem of _push_ architectures.

I'd be favouring a _pull_ approach: job is complete when the acknowledgment has been sent in a pubsub system. Then when the remote services are operational, they withdraw the message from the pubsub queue after having processed it.

**Comment by abulte** [comment]
@oncletom thanks for the feedback. I think we need to talk face to face about what you said ;-)
