### ISSUE TITLE
Hash collision

### ISSUE THREAD

**Issue by abulte** [opendatateam/croquemort#26]
Currently group names and urls are hashed and stored as keys at the "root" of the Redis DB. So if a group's name is an url (strange but possible), this will result in some shady behavior - yet it does not crash.

Best practice would be to prepend hashes with a namespace, e.g. `url:<hash>`, `group:<hash>`...

**Comment by oncletom** [comment]
Pushing it a bit further, could it happen a hash collides within the same namespace? (like `url` or `group`). I mean, how likely two hashes can collide — I don't know which algorithm is used under the hood.

**Comment by abulte** [comment]
@oncletom feel free to do the math ;-) `hashlib.md5(value.encode('utf-8')).hexdigest()[:8]`

I'm not very worried about that.
